version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: filevault-db
    ports:
      - "5433:5432"  # Мы будем подключаться к базе через 5433
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=filevault_db

  s3:
    image: minio/minio
    container_name: filevault-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://s3:9000 minioadmin minioadmin) do echo 'Waiting for Minio...' && sleep 1; done;
      /usr/bin/mc mb local/uploads || true;
      exit 0;
      "

  redis:
    image: redis:7-alpine
    container_name: filevault-redis
    ports:
      - "6379:6379"